name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      tf_workspace:
          required: true
          type: string
      commit_hash:
          required: true
          type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ inputs.tf_workspace }}
        configuration-path: ${{ inputs.service_name }}
        commit_hash: ${{inputs.commit_hash}}
