name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service_names:
        required: true
        type: string
      tf_workspace:
          required: true
          type: string
      commit_hash:
          required: true
          type: string
          
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        
      # Use the latest commit hash in subsequent steps or jobs
    - name: Use latest commit hash
      run: |
        echo "${{ inputs.tf_workspace }}"
        echo "${{ inputs.service_names }}"
        echo "${{inputs.commit_hash}}"
        cat 565
        ls -lah

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Your commit message'
        new_branch: 353-branch
      

    - name: create pull request
      run: gh pr create -B main -H 353-branch --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
